<a href="https://colab.research.google.com/github/jakobbaumgartner/CNN-HotDog-Classifier/blob/master/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow.keras as keras

In [8]:
keras.__version__

'2.4.0'

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

Nastavimo poti do fotografij, uredimo fotografije. In izdelamo training dataset.

In [10]:
categories = ["hot_dog", "not_hot_dog"]
datadir = "drive/MyDrive/Colab Notebooks/seefood/train"
os.getcwd()
IMG_SIZE = 100 # maybe change this setting later, if the results are not good

training_data = []

for category in categories:  # do hot_dog and not_hot_dog

    path = os.path.join(datadir,category)  # create path to hotdogs
    class_num = categories.index(category)  # get the classification  (0 or a 1). hot or not

    for img in tqdm(os.listdir(path)):  # iterate over each image 
        img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to grayscale array
        new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE)) # resize 
        training_data.append([new_array, class_num]) 
      
    


100%|██████████| 248/248 [00:34<00:00,  7.14it/s]

100%|██████████| 249/249 [01:34<00:00,  2.64it/s]


Sedaj želimo premešati podatke, da niso vse slike kategorij po vrsti, drugače imamo težave z učenjem.

In [11]:
import random
random.shuffle(training_data)

In [12]:
for sample in training_data[:10]: # lets check if it is well shuffled 
    print(sample[1])

0
1
0
1
1
1
1
0
0
0


In [13]:
X = []   # features (big X)
y = []   # labels (small y)

for features,label in training_data:
    X.append(features) 
    y.append(label)   # labels

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

# we have to make features into a np array
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1) # number of features, size_x, size_y, colors (grayscale = 1)

[[[[15]
   [16]
   [15]
   ...
   [13]
   [ 9]
   [13]]

  [[14]
   [ 8]
   [ 7]
   ...
   [ 5]
   [ 5]
   [14]]

  [[15]
   [10]
   [ 9]
   ...
   [13]
   [11]
   [14]]

  ...

  [[18]
   [56]
   [91]
   ...
   [ 2]
   [ 3]
   [14]]

  [[23]
   [68]
   [87]
   ...
   [ 2]
   [ 2]
   [14]]

  [[16]
   [45]
   [15]
   ...
   [16]
   [16]
   [17]]]]
